"""
This is a setup.py script generated by py2applet
"""
#! not working

from setuptools import setup

APP = ['app_usage.py']
DATA_FILES = []
OPTIONS = {
    'iconfile': 'resources/icon.icns',
    'plist': {
        'CFBundleName': 'app_usage-2.0',
        'CFBundleShortVersionString': '2.0',
        'CFBundleVersion': '2.0',
    },
    'argv_emulation': True,  # Enables double-clicking in Finder
    'packages': ['psutil'],  #* Include necessary packages
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
